name: LAMBDA-FLIX
title: Lambda-flix | Idea Blog
description: LAMBDA-FLIX is a platform that upload our news and stories.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: lambdaflix
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
